# Numpy

In [1]:
import numpy as np

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
arr = np.random.uniform(0,20,[4,7])

In [3]:
arr/20

array([[0.94245975, 0.89153568, 0.64805515, 0.359112  , 0.4492865 ,
        0.12668847, 0.08544916],
       [0.23078812, 0.98483844, 0.50261223, 0.00978343, 0.18769702,
        0.93157548, 0.20849014],
       [0.60131704, 0.92813116, 0.35708184, 0.69618857, 0.14280841,
        0.17271368, 0.97997439],
       [0.48125217, 0.28595738, 0.00723018, 0.01260487, 0.61587246,
        0.96080935, 0.274306  ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.uniform(0, 10, [8, 10])
print(arr.sum(axis=1).argmin())
print(arr[arr.sum(axis=1).argmin()])

2
[1.76564873 5.05492268 0.46082325 0.4897412  0.29908313 5.57144065
 2.47751803 5.06282722 4.00756594 5.60498853]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
def Euklid(arr1, arr2):
    return (sum((arr1 - arr2)**2))**(0.5)

In [6]:
Euklid(np.array([0, 1]), np.array([1, 0]))

1.4142135623730951

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [7]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [8]:
from numpy.linalg import inv

np.dot(np.dot((inv(A)),(-C)),(inv(B)))

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
arr = np.loadtxt('01_numpy_data/minutes_n_ingredients.csv', dtype = 'int32', skiprows=1, delimiter=',')
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [10]:
print('min - ',arr[:,1:].min())
print('max -',arr[:,1:].max())
print('median -',np.median(arr[:,1:]))

min -  0
max - 2147483647
median - 13.0


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
arr[np.random.randint(0, len(arr),[1, 10])]

array([[[328336,     32,     12],
        [350174,     20,     14],
        [218852,     23,      9],
        [157053,     15,     11],
        [493762,    380,     19],
        [196902,     25,     13],
        [246582,      5,      8],
        [ 88108,     80,     14],
        [273890,     20,     12],
        [340291,     35,      9]]])

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [12]:
arr_num_5 = arr[arr[:,2] <= 5] 

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [13]:
sum(arr[:, 2] < arr[:, 2].mean())/len(arr)

0.58802

6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [14]:
arr_copy = arr.copy()

In [15]:
quant = np.quantile(arr_copy, 0.75, axis = 0)[1]
quant

65.0

In [16]:
arr_copy[arr_copy[:, 1] > quant] = quant

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [17]:
sum(arr[:, 1] == 0)

479

In [18]:
arr_copy[arr[:, 1] == 0] = 1

In [19]:
sum(arr[:, 1] == 0)

479

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [25]:
np.unique(arr[:,2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

In [40]:
line = np.array([i for i in range(1, 42)])
line[np.isin(line ,np.unique(arr[:,2]), invert= True)]

array([36, 38, 40, 41])

9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [48]:
warn_mass = arr[:,2]/arr[:,1]
warn_mass[warn_mass[:] == np.inf] = 0
max(warn_mass)

C:\Users\jay\AppData\Local\Temp\ipykernel_7276\4279680145.py:1: RuntimeWarning: divide by zero encountered in divide
  warn_mass = arr[:,2]/arr[:,1]


23.0

10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [81]:
top_100 = np.sort(arr, axis = 0)[-101, 1]
arr[arr[:, 1] >= top_100][:,2].mean()

6.617647058823529

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [104]:
mask = (arr[:, 1] <= 20) * (arr[:, 2] <= 5) + 0
np.c_[arr, mask]

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [133]:
mask_1 = arr[:, 1] < 10
mask_3 = arr[:, 1] > 20
mask_2 = np.logical_not(np.logical_or(mask_1,mask_3))

minimum = min(sum(mask_1),sum(mask_2),sum(mask_3))

third = np.array([arr[mask_1][:minimum], arr[mask_2][:minimum], arr[mask_3][:minimum]])
third.shape

(3, 7588, 3)

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [126]:
np.array([5 for i in range(minimum)])

array([5, 5, 5, ..., 5, 5, 5])

In [127]:
np.array([10 for i in range(minimum)])

array([10, 10, 10, ..., 10, 10, 10])

In [136]:
for i in range(3):
    print('Простота рецепта - ', i,' - ' ,sum(third[i,:10,1] * 5 + third[i,:10,2] * 10))

Простота рецепта -  0  -  835
Простота рецепта -  1  -  1450
Простота рецепта -  2  -  4430
